//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mr.Programmer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mr.Programmer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1471896_646482435398412_1468404596_n {
            get {
                object obj = ResourceManager.GetObject("_1471896_646482435398412_1468404596_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _587777 {
            get {
                object obj = ResourceManager.GetObject("_587777", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5b01e5b8f939355d1b38858b23b1e4d8 {
            get {
                object obj = ResourceManager.GetObject("_5b01e5b8f939355d1b38858b23b1e4d8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 This is my first lab project of second year first semester . This program is based on what i learned throughout these one and a half year  in programming  . Of course i have many things to learn so this program does not have many algorithms which i don&apos;t know yet. The resources are from which i myself learned from . It took me y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about_me {
            get {
                return ResourceManager.GetString("about_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 Here are some links for starting with ad hoc problems\par
        ///1.\par
        ///{{\field{\*\fldinst{HYPERLINK https://www.urionlinejudge.com.br/judge/en/problems/index/1 }}{\fldrslt{https://www.urionlinejudge.com.br/judge/en/problems/index/1\ul0\cf0}}}}\f0\fs22\par
        ///Uri Has some pretty easy problmes. Suits [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ad_hoc {
            get {
                return ResourceManager.GetString("Ad_hoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fswiss\fprq2\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 First learn BFS algorithm from these links or you can search google on your own and find the resource that suits your learning.\par
        ///\par
        ///Here are some resources :-\par
        ///
        ///\pard\widctlpar\sa160\sl252\slmult1 {\f1\fs24\lang1033{\field{\*\fldinst{HYPERLINK h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bfs {
            get {
                return ResourceManager.GetString("Bfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 Binary search is a very important search tecnique.\par
        ///First learn Binary search algorithm from these links or you can search google on your own and find the resource that suits your learning.\par
        ///\par
        ///Here are some resources\par
        ///{{\field{\*\fldinst{HYPERLINK http://www.dave-reed.com/book/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string binary_search_algorithm {
            get {
                return ResourceManager.GetString("binary_search_algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 Bitwise tecniques are very important for programming . Beacause everything is 1 and 0 :D .\par
        ///Here are some links\par
        ///{{\field{\*\fldinst{HYPERLINK http://zobayer.blogspot.com/2009/12/bitwise-operations-in-cc-part-1.html }}{\fldrslt{http://zobayer.blogspot.com/2009/12/bitwise-operations-in- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bitwise_tecniques {
            get {
                return ResourceManager.GetString("Bitwise_tecniques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 First learn bubble sort algorithm from these links or you can search google on your own and find the resource that suits your learning.\par
        ///{{\field{\*\fldinst{HYPERLINK https://en.wikipedia.org/wiki/Bubble_sort }}{\fldrslt{https://en.wikipedia.org/wiki/Bubble_sort\ul0\cf0}}}}\f0\fs22\par
        ///{{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bubble_sort {
            get {
                return ResourceManager.GetString("Bubble_sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs36\lang9 Copying is disabled in this whole software . You Should and write the code yourself rather than copy paste . It will help clearing your concept on what you learned .\par
        /// Copy paste is a bad habit .  \fs22\par
        ///}
        ///.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fswiss\fprq2\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 First learn DFS algorithm from these links or you can search google on your own and find the resource that suits your learning.\par
        ///\par
        ///Here are some resources :-\par
        ///
        ///\pard\widctlpar\sa160\sl252\slmult1 {\f1\fs24\lang1033{\field{\*\fldinst{HYPERLINK h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DFS {
            get {
                return ResourceManager.GetString("DFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fswiss\fprq2\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\widctlpar\sa160\sl252\slmult1\f0\fs22\lang9 First learn \f1\fs24\lang1033 Dijkstra \f0\fs22\lang9 algorithm from these links or you can search google on your own and find the resource that suits your learning.\par
        ///
        ///\pard\sa200\sl276\slmult1 Here are some resources :-\par
        ///{{\field{\*\fldi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dijkstra {
            get {
                return ResourceManager.GetString("dijkstra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fswiss\fprq2\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 First learn Disjoint set algorithm from these links or you can search google on your own and find the resource that suits your learning.\par
        ///Here are some resources :-\par
        ///
        ///\pard\widctlpar\sa160\sl252\slmult1 {{\field{\*\fldinst{HYPERLINK https://www.you [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Disjoint_set_data_structure {
            get {
                return ResourceManager.GetString("Disjoint_set_data_structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fswiss\fprq2\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 First learn Binary search algorithm from these links or you can search google on your own and find the resource that suits your learning.\par
        ///Here are some resources\f1\fs24\lang1033\par
        ///
        ///\pard\widctlpar\sa160\sl252\slmult1 {{\field{\*\fldinst{HYPERLINK  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eular_phi_function {
            get {
                return ResourceManager.GetString("eular_phi_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Courier New;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red117\green117\blue117;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sl240\slmult1\cf1\f0\fs20\lang9\par
        ///\f1\fs28 #include &lt;stdio.h&gt;\par
        ///\~\par
        ///void multiply(int F[2][2], int M[2][2]);\par
        ///\~\par
        ///void power(int F[2][2], int n);\par
        ///\~\par
        ////* function that returns nth Fibonacci number */\par
        ///int fib(int n)\par
        ///\{\par
        ///\~\~int F[2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FIbonacci_matrix_multiplication {
            get {
                return ResourceManager.GetString("FIbonacci_matrix_multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fswiss\fprq2\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 First learn Floyed warshall algorithm from these links or you can search google on your own and find the resource that suits your learning.\par
        ///\par
        ///Here are some resources\par
        ///{{\field{\*\fldinst{HYPERLINK https://www.youtube.com/watch?v=8TRX85-myD4 }}{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string floyed_warshall {
            get {
                return ResourceManager.GetString("floyed_warshall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 Here are some links\par
        ///{{\field{\*\fldinst{HYPERLINK https://en.wikipedia.org/wiki/Greatest_common_divisor }}{\fldrslt{https://en.wikipedia.org/wiki/Greatest_common_divisor\ul0\cf0}}}}\f0\fs22  {{\field{\*\fldinst{HYPERLINK https://en.wikipedia.org/wiki/Least_common_multiple }}{\fldrslt{http [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gcd_lcm {
            get {
                return ResourceManager.GetString("gcd_lcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fswiss\fprq2\fcharset0 Calibri;}{\f2\fswiss\fprq2\fcharset0 Berlin Sans FB Demi;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 First learn kruskal mst algorithm from these links or you can search google on your own and find the resource that suits your learning.\par
        ///Here are some resources :-\par
        ///
        ///\pard\widctlpar\sa160\sl252\slmul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kruskal_mst {
            get {
                return ResourceManager.GetString("kruskal_mst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fswiss\fprq2\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 Famous Book of Halim Brothers {{\field{\*\fldinst{HYPERLINK http://bookzz.org/book/2514434/ec6b35/?_ir=1 }}{\fldrslt{http://bookzz.org/book/2514434/ec6b35/?_ir=1\ul0\cf0}}}}\f0\fs22\par
        ///An awesome programming blog written in bangla by shafaet vai {{\field{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fswiss\fprq2\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 Modified sieve\par
        ///memset(ara,0,sizeof(ara));\par
        ///for(int i = 2; i &lt;= upper_limit; i++)\par
        ///\{\par
        ///\tab if(ara[i]==0)\par
        ///\tab\{\par
        ///\tab\tab for(int j = i; j &lt;= unpper_limit; j++)\par
        ///\tab\tab\tab ara[j]++;\par
        ///\tab\}\par
        ///\}\par
        ///\f1\fs24\lang1033 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Modified_sieve {
            get {
                return ResourceManager.GetString("Modified_sieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\widctlpar\sa160\sl252\slmult1\f0\fs24 Here are some links\par
        ///{{\field{\*\fldinst{HYPERLINK https://en.wikipedia.org/wiki/Modular_exponentiation }}{\fldrslt{https://en.wikipedia.org/wiki/Modular_exponentiation\ul0\cf0}}}}\f0\fs24\par
        ///{{\field{\*\fldinst{HYPERLINK https://discuss.codechef. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Modular_Exponention {
            get {
                return ResourceManager.GetString("Modular_Exponention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will happen if in a C program you assign a value to an array element whose subscript exceeds the size of array?
        ///The element will be set to 0.
        ///The compiler would report an error.
        ///The program may crash if some important data gets overwritten.
        ///The array size would appropriately grow.
        ///What does the following declaration mean? int (*ptr)[10];
        ///ptr is array of pointers to 10 integers
        ///ptr is a pointer to an array of 10 integers
        ///ptr is an array of 10 integers
        ///ptr is an pointer to array
        ///In C, if you pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string New_Text_Document__2_ {
            get {
                return ResourceManager.GetString("New_Text_Document__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap opening {
            get {
                object obj = ResourceManager.GetObject("opening", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 You can work with the prime numbers and find number of factors , number of distinct factors, number of divisors , eular phi from factorization algorithm . I have given algorithm for counting number of prime factors of certain number. Do the rest on your own. Don&apos;t skip the other like eular phi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prime_factorization {
            get {
                return ResourceManager.GetString("prime_factorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap programming {
            get {
                object obj = ResourceManager.GetObject("programming", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 Recursion is very fundamental and very very important topic in programming . Very complex word can be done very easily by recursion . But it is quite difficul to understand it . But it is very important . Many algorithms use recursion . so you must learn it properly.\par
        ///Here are some resourc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string recursion {
            get {
                return ResourceManager.GetString("recursion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9\par
        ///First learn Sieve algorithm from these links or you can search google on your own and find the resource that suits your learning.\par
        ///{{\field{\*\fldinst{HYPERLINK http://lightoj.com/article_show.php?article=1001 }}{\fldrslt{http://lightoj.com/article_show.php?article=1001\ul0\cf0}}}}\f0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sieve {
            get {
                return ResourceManager.GetString("sieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 The Information in this software specializes in efficient algorithims. I assumed that you have basic knowledge in programming , you are good in c and want to start c++ and you know the all basic algorithms like bubble sort , gcd lcm etc. If you find anything new in code search it on google and learn about it . Copy paste in not  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Something_to_know {
            get {
                return ResourceManager.GetString("Something_to_know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 Stl or Standard Template Library is very important for contest programming. Here are some resources where you can learn stl.First learn STL from these links or you can search google on your own and find the resource that suits your learning.\par
        ///\par
        ///1.\par
        ///{{\field{\*\fldinst{HYPERLINK htt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stl {
            get {
                return ResourceManager.GetString("stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fswiss\fprq2\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs22\lang9 First learn Topological sort algorithm from these links or you can search google on your own and find the resource that suits your learning.\par
        ///Here are some resources :-\par
        ///{{\field{\*\fldinst{HYPERLINK http://www.shafaetsplanet.com/planetcoding/?p=848 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string topological_sort {
            get {
                return ResourceManager.GetString("topological_sort", resourceCulture);
            }
        }
    }
}
